export const ASSETS = {
  logos: {
    light: "/assets/images/logo-light.svg",
    dark: "/assets/images/logo-dark.svg"
  },
  profile: "/assets/images/VedhaProfile.jpeg",
  ogImage: "/assets/images/og-image.jpeg",
  blog: {
    fatherForgets: {
      src: "/assets/blog/father-forgets.png",
      alt: "Path of Light",
      caption: "Illustration generated by ChatGPT"
    },
    publicSpeakingLesson: {
      src: "/assets/blog/public-speaking-lesson.png",
      alt: "A nervous speaker at a podium while a mentor demonstrates clear communication with an analogy",
      caption: "Illustration generated by Gemini"
    },
    sdeToFde: {
      src: "/assets/blog/sde-to-fde.png",
      alt: "A stick figure standing at a fork in the road",
      caption: "Illustration generated by ChatGPT"
    }
  },
  projects: {
    defaultCover: "/assets/projects/default-cover.png",
    focusGrid: "/assets/projects/focusgrid.png",
    rewardRally: "/assets/projects/rewardrally.png",
    devType: "/assets/projects/devtype.png",
    carouselStudio: "/assets/projects/carouselstudio.png"
  }
};
